Update function
Debloat and comments fixes.

Signed-off-by: Harry Kurn <findarr@pm.me>

diff --git a/toolchain/function b/toolchain/function
--- a/toolchain/function
+++ b/toolchain/function
@@ -1,33 +1,23 @@
 #!/usr/bin/env sh
 export LC_ALL=C LANG=C; . "$(dirname ${0})/heiwa.conf"
 
-# ~~~~~~~
-
-HEIWA="$(sh -c "echo ${TGT_ROOTFS}")"     # Target ROOT (/) FileSystem.
+HEIWA="$(sh -c "echo ${TGT_ROOTFS}")"     # Target root (/) FileSystem.
 CRS_TOOLS="clang1-tools"                  # Stage 1 Clang/LLVM Cross-Toolchain.
 TMP_TOOLS="clang2-tools"                  # Stage 2 Clang/LLVM and Temporary Tools.
-DISTFILES="$(dirname ${0})/../distfiles"  # Distribution files (package tarballs).
+DISTFILES="$(dirname ${0})/../distfiles"  # Distribution files (tarballs) path.
 REPO_CORE="$(dirname ${0})/../syscore"    # Syscore local repository path.
-CCACHE_DIR="$(dirname ${0})/../ccache"    # Ccache directory.
+CCACHE_DIR="$(dirname ${0})/../ccache"    # Ccache directory path.
 
 export HEIWA CRS_TOOLS TMP_TOOLS DISTFILES REPO_CORE CCACHE_DIR
 
-# ~~~~~~~
-
 G="\033[1;32m" B="\033[1;34m" M="\033[1;35m" R="\033[1;31m" NC="\033[0m" \
 g="\033[0;32m" b="\033[0;34m" m="\033[0;35m" r="\033[0;31m" # ANSI Color.
-
-# ~~~~~~~
 
 msg() { printf "${G} > ${NC}${@}\n"; }
 hdr() { printf "${B}*${M}) ${NC}${@}\n"; }
 die() { >&2 printf "${R}error:${NC} ${@}\n"; exit 1; }
 
-# ~~~~~~~
-
 iof() { [ ${1} = ON ] && :; }
-
-# ~~~~~~~
 
 get_privilege() {
     [ -x "$(command -v doas)" ] && PRIV="doas" || :
@@ -35,16 +25,14 @@ get_privilege() {
     [ -n "$PRIV" ] || die "${m}sudo${NC} nor ${m}doas${NC} not found!"
 }
 
-# ~~~~~~~
-
 version_check() {
     hdr "Checking host system requirements"
     if [ -x "$(dirname ${0})/../version-check" ]; then
-        "$(dirname ${0})/../version-check" x || die "Failed to check host system requirements!"
+        if ! "$(dirname ${0})/../version-check" x; then
+            die "Failed to check host system requirements!"
+        fi
     fi
 }
-
-# ~~~~~~~
 
 prepare_tools() {
     if [ "${EUID:-$(id -u)}" -ne 0 ]; then
@@ -60,11 +48,12 @@ prepare_tools() {
             [ -d "${HEIWA}/${CRS_TOOLS}" ] || { msg "Creating ${m}${CRS_TOOLS}${NC}"  ; ${ASRT} mkdir -pv "${HEIWA}/${CRS_TOOLS}"; }
             [ -d "${HEIWA}/${TMP_TOOLS}" ] || { msg "Creating ${m}${TMP_TOOLS}${NC}"  ; ${ASRT} mkdir -pv "${HEIWA}/${TMP_TOOLS}"; }
             
-            
             for DIR in "$CRS_TOOLS" "$TMP_TOOLS"; do
                 if [ "$(readlink -f "/${DIR}")" != "${HEIWA}/${DIR}" ]; then
                     msg "Symlink ${m}/${DIR}${NC} ${r}[forced]${NC}"
-                    ${PRIV} ln -sfv "${HEIWA}/${DIR}" / || die "Failed to symlink ${m}/${DIR}${NC}!"
+                    if ! ${PRIV} ln -sfv "${HEIWA}/${DIR}" /; then
+                        die "Failed to symlink ${m}/${DIR}${NC}!"
+                    fi
                 fi
             done; unset DIR
             
@@ -75,7 +64,9 @@ prepare_tools() {
                 for DIR in "$CRS_TOOLS" "$TMP_TOOLS"; do
                     if [ "$(stat -c '%U' "${HEIWA}/${DIR}")" != "$USER" ]; then
                         msg "Changing the ${m}${DIR}${NC} owner to ${g}${USER}${NC} ${r}[forced]${NC}"
-                        ${ASRT} chown -hRv "$USER":"$USER" "${HEIWA}/${DIR}" || die "Failed to ${m}chown${NC} ${m}${DIR}${NC}!"
+                        if ! ${ASRT} chown -hRv "$USER":"$USER" "${HEIWA}/${DIR}"; then
+                            die "Failed to ${m}chown${NC} ${m}${DIR}${NC}!"
+                        fi
                     fi
                 done; unset DIR
             fi
